name: Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # mainブランチにpushされたら実行

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t number-recognition-cnn:latest .

      - name: Tag image
        run: docker tag number-recognition-cnn:latest nenneko1729/number-recognition-cnn:latest

      - name: Push image
        run: docker push nenneko1729/number-recognition-cnn:latest